import sqlite3
import os

class job_type_db():

    def __init__(self):
        self.job_type_db = "/Users/tylehman/Desktop/cjap_vm/django/cjap/cjap_engine/js_data/job_type.db"
        try:
            os.remove(self.job_type_db)
        except:
            pass
        self.job_type_list = [
            ('Accounting/Finance', 'accounting', 'Accountant'),
            ('Accounting/Finance', 'accountant', 'Accountant'),
            ('Accounting/Finance', 'accounts', 'Ar/Ap'),
            ('Accounting/Finance', 'account s', 'Ar/Ap'),
            ('Accounting/Finance', 'tax', 'Auditor'),
            ('Accounting/Finance', 'audit', 'Auditor'),
            ('Accounting/Finance', 'bookkeep', 'Bookkeeper'),
            ('Accounting/Finance', 'Controller', 'Controller'),
            ('Accounting/Finance', 'finance', 'Finance'),
            ('Admin and Office', 'admin', 'Administrative Assistant'),
            ('Admin and Office', 'clerk', 'Clerk'),
            ('Admin and Office', 'office', 'Office Administrator'),
            ('Admin and Office', 'recept', 'Receptionist'),
            ('Admin and Office', 'front desk', 'Receptionist'),
            ('Admin and Office', 'Secretary', 'Secretary'),
            ('Admin and Office', 'desktop', 'Secretary'),
            ('Analyst', 'analy', 'Analyst'),
            ('Auto', 'diesel', 'Diesel Worker'),
            ('Auto', 'car ', 'Mechanic'),
            ('Auto', 'automotive', 'Mechanic'),
            ('Auto', 'auto', 'Mechanic'),
            ('Auto', 'mechanic', 'Mechanic'),
            ('Auto', 'mechanical', 'Mechanic'),
            ('Business', 'bank', 'Bank Positions'),
            ('Business', 'teller', 'Bank Teller'),
            ('Business', 'Business Dev', 'Business Dev'),
            ('Business', 'Business*.operation', 'Business Operations'),
            ('Business', 'busi', 'Business Ops'),
            ('Business', 'buy', 'Buyer'),
            ('Business', 'collections', 'Collections'),
            ('Business', 'Compli', 'Compliance'),
            ('Business', 'credit', 'Credit Analyst'),
            ('Business', 'estimat', 'Estimator'),
            ('Business', 'human res', 'Hr'),
            ('Business', 'hr*. rep', 'Hr'),
            ('Business', 'Lender', 'Lender'),
            ('Business', 'Loan', 'Loan Officer'),
            ('Business', 'marketing', 'Marketing'),
            ('Business', 'product manager', 'Product Manager'),
            ('Business', 'project manager', 'Project Manager'),
            ('Business', 'project', 'Project Resource'),
            ('Business', 'quality', 'Qa'),
            ('Business', 'scheduler', 'Scheduler'),
            ('Cleaner/Housekeeper', 'clean', 'Cleaner'),
            ('Cleaner/Housekeeper', 'Custodian', 'Custodian'),
            ('Cleaner/Housekeeper', 'house cleaner', 'House Cleaner'),
            ('Cleaner/Housekeeper', 'housekee', 'Housekeeper'),
            ('Cleaner/Housekeeper', 'Janitor', 'Janitor'),
            ('Cleaner/Housekeeper', 'laundry', 'Laundry'),
            ('Construction', 'concrete', 'Concrete Worker'),
            ('Construction', 'hydro', 'Construction Worker'),
            ('Construction', 'construction', 'Construction Worker'),
            ('Construction', 'hvac', 'HVAC'),
            ('Construction', 'roof', 'Roofer'),
            ('Construction', 'weld', 'Welder'),
            ('Contractor', 'drywall', 'Drywaller'),
            ('Contractor', 'floor', 'Floorer'),
            ('Contractor', 'paint', 'Painter'),
            ('Contractor', 'remodel', 'Remodeler'),
            ('Contractor', 'repair', 'Repairer'),
            ('Customer Service', 'client service', 'Client Services'),
            ('Customer Service', 'rep', 'Customer Service Representivitive'),
            ('Customer Service', 'representative', 'Customer Service Representivitive'),
            ('Customer Service', 'customer', 'Customer Service Representivitive'),
            ('Customer Service', 'csr', 'Customer Service Representivitive'),
            ('Disability', 'Disab', 'Disability Oriented Position'),
            ('Driver/Transportation', 'cdl', 'Cdl Driver'),
            ('Driver/Transportation', 'truck', 'Cdl Driver'),
            ('Driver/Transportation', 'courier', 'Courier'),
            ('Driver/Transportation', 'driv', 'Driver'),
            ('Driver/Transportation', 'delivery', 'Driver'),
            ('Driver/Transportation', 'transport', 'Transporter'),
            ('Driver/Transportation', 'uber', 'Uber'),
            ('Education', 'Career Coach', 'Career Coach'),
            ('Education', 'instructor', 'Instructor'),
            ('Education', 'teacher', 'Teacher'),
            ('Education', 'tutor', 'Tutor'),
            ('Engineer', 'design', 'Designer'),
            ('Engineer', 'engineer', 'Engineer'),
            ('Environment', 'Environm', 'Environment Worker'),
            ('Laborer', 'carpenter', 'Carpenter'),
            ('Laborer', 'cement', 'Cement Worker'),
            ('Laborer', 'crew', 'Crew Member'),
            ('Laborer', 'Event S', 'Event Specialits'),
            ('Laborer', 'farm', 'Farmer'),
            ('Laborer', 'flag', 'Flagger'),
            ('Laborer', 'forest', 'Forest Worker'),
            ('Laborer', 'help wanted', 'General Helper'),
            ('Laborer', 'ground', 'Grounds Keeper'),
            ('Laborer', 'labor', 'Laborer'),
            ('Laborer', 'laborer', 'Laborer'),
            ('Laborer', 'landscape', 'Landscaper'),
            ('Laborer', 'lawn', 'Lawn Worker'),
            ('Laborer', 'yard', 'Lawn Worker'),
            ('Laborer', 'Loader', 'Loader'),
            ('Laborer', 'Massage', 'Massage'),
            ('Laborer', 'mover', 'Mover'),
            ('Laborer', 'pipe', 'Pipe Worker'),
            ('Laborer', 'porter', 'Porter'),
            ('Laborer', 'Sanitation', 'Sanitation Worker'),
            ('Legal/Architect', 'Architect', 'Architect'),
            ('Legal/Architect', 'attorney', 'Attorney'),
            ('Legal/Architect', 'lawyer', 'Lawyer'),
            ('Legal/Architect', 'legal', 'Paralegal'),
            ('Maintenance', 'maintenance', 'Maintenance'),
            ('Manager', 'GM', 'General Manager'),
            ('Manager', 'manager', 'Manager'),
            ('Manager', 'manage', 'Store Manager'),
            ('Manufacturing', 'assemb', 'Assembler'),
            ('Manufacturing', 'Build', 'Builder'),
            ('Manufacturing', 'equip', 'Equiptment'),
            ('Manufacturing', 'fabricat', 'Fabricator'),
            ('Manufacturing', 'foreman', 'Foreman'),
            ('Manufacturing', 'handler', 'Handler'),
            ('Manufacturing', 'installer', 'Installer'),
            ('Manufacturing', 'machin', 'Machinist'),
            ('Manufacturing', 'manufacture', 'Manufacturor'),
            ('Manufacturing', 'metal', 'Metal Worker'),
            ('Manufacturing', 'operator', 'Operator'),
            ('Manufacturing', 'product', 'Production Worker'),
            ('Manufacturing', 'production', 'Production Worker'),
            ('Medical/Healthcare', 'diet', 'Aide'),
            ('Medical/Healthcare', 'patient', 'Care Taker'),
            ('Medical/Healthcare', 'dental', 'Dental Assistant'),
            ('Medical/Healthcare', 'medical', 'Medical Assistant'),
            ('Medical/Healthcare', 'prn ', 'Nurse'),
            ('Medical/Healthcare', 'rn ', 'Nurse'),
            ('Medical/Healthcare', 'nurs', 'Nurse'),
            ('Medical/Healthcare', 'clinic', 'Nurse'),
            ('Medical/Healthcare', 'C.N.A', 'Nurse'),
            ('Medical/Healthcare', 'CNA', 'Nurse'),
            ('Medical/Healthcare', 'nutrit', 'Nutritionist'),
            ('Non-profit/Government', 'Crime Scene Clean', 'Crime Scene Cleaner'),
            ('Non-profit/Government', 'Dispatch', 'Dispatcher'),
            ('Non-profit/Government', 'Dispenser', 'Dispensery Worker'),
            ('Non-profit/Government', 'Volunteer', 'Volunteer'),
            ('Restaurant/Bar', 'bake', 'Baker'),
            ('Restaurant/Bar', 'Barista', 'Barista'),
            ('Restaurant/Bar', 'bar', 'Bartender'),
            ('Restaurant/Bar', 'bartender', 'Bartender'),
            ('Restaurant/Bar', 'busser', 'Busser'),
            ('Restaurant/Bar', 'meat', 'Butcher'),
            ('Restaurant/Bar', 'banquet', 'Caterer'),
            ('Restaurant/Bar', 'cater', 'Caterer'),
            ('Restaurant/Bar', 'chef', 'Chef'),
            ('Restaurant/Bar', 'Cocinero', 'Chef'),
            ('Restaurant/Bar', 'cook', 'Chef'),
            ('Restaurant/Bar', 'Culinary', 'Chef'),
            ('Restaurant/Bar', 'kitchen', 'Chef'),
            ('Restaurant/Bar', 'prep', 'Chef'),
            ('Restaurant/Bar', 'sandwich', 'Chef'),
            ('Restaurant/Bar', 'sous', 'Chef'),
            ('Restaurant/Bar', 'Concierge', 'Concierge'),
            ('Restaurant/Bar', 'line', 'Cook'),
            ('Restaurant/Bar', 'counter', 'Counter Worker'),
            ('Restaurant/Bar', 'Deli ', 'Deli'),
            ('Restaurant/Bar', 'Delivery Driver', 'Delivery Driver'),
            ('Restaurant/Bar', 'dish', 'Dishwasher'),
            ('Restaurant/Bar', 'dishwasher', 'Dishwasher'),
            ('Restaurant/Bar', 'hotel', 'Hospitality Worker'),
            ('Restaurant/Bar', 'host', 'Host'),
            ('Restaurant/Bar', 'foh', 'Host'),
            ('Restaurant/Bar', 'front', 'Host'),
            ('Restaurant/Bar', 'pizza', 'Pizza Person'),
            ('Restaurant/Bar', 'expo', 'Server'),
            ('Restaurant/Bar', 'wait', 'Server'),
            ('Restaurant/Bar', 'drink', 'Server'),
            ('Restaurant/Bar', 'Breakfast', 'Server'),
            ('Restaurant/Bar', 'Concessionist', 'Server'),
            ('Restaurant/Bar', 'food', 'Server'),
            ('Restaurant/Bar', 'restaurant', 'Server'),
            ('Restaurant/Bar', 'froze', 'Server'),
            ('Restaurant/Bar', 'dining', 'Server'),
            ('Restaurant/Bar', 'server', 'Server'),
            ('Restaurant/Bar', 'subway', 'Server'),
            ('Retail', 'cashier', 'Cashier'),
            ('Retail', 'grocery', 'Grocery'),
            ('Retail', 'merchan', 'Merchandiser'),
            ('Retail', 'produce', 'Produce Worker'),
            ('Retail', 'store', 'Retail Associate'),
            ('Retail', 'retail', 'Retail Associate'),
            ('Retail', 'shift', 'Retail Associate'),
            ('Retail', 'team member', 'Retail Associate'),
            ('Sales/Account Management', 'Account Executive', 'Account Executive'),
            ('Sales/Account Management', 'account manager', 'Account Manager'),
            ('Sales/Account Management', 'sale', 'Sales'),
            ('security', 'security', 'Security'),
            ('Service', 'Barber', 'Barber'),
            ('Service', 'salon', 'Salon'),
            ('Service', 'spa', 'Spa Worker'),
            ('Systems/Software', 'developer', 'Developer'),
            ('Systems/Software', 'develop', 'Developer'),
            ('Systems/Software', 'mobile', 'Mobile Developer'),
            ('Systems/Software', 'programmer', 'Programmer'),
            ('Systems/Software', 'software', 'Software Developer'),
            ('Systems/Software', 'system', 'Systems'),
            ('Trade/Technician', 'apprentice', 'Apprentice'),
            ('Trade/Technician', 'electrical', 'Electrician'),
            ('Trade/Technician', 'electrician', 'Electrician'),
            ('Trade/Technician', 'journeyman', 'Journeyman'),
            ('Trade/Technician', 'oil', 'Oil Worker'),
            ('Trade/Technician', 'plumb', 'Plumber'),
            ('Trade/Technician', 'plumber', 'Plumber'),
            ('Trade/Technician', 'support tech', 'Support Tech'),
            ('Trade/Technician', 'tech', 'Technician'),
            ('Trade/Technician', 'Utili', 'Utility Worker'),
            ('Warehouse', 'fork', 'Fork Lift Operator'),
            ('Warehouse', 'warehouse', 'Warehouse Associate'),
            ]

    def db_create(self):
        self.conn = sqlite3.connect(self.job_type_db)
        self.c = self.conn.cursor()
        self.c.execute('CREATE TABLE job_type_data '
                                   '(job_category CHAR(50), job_regex CHAR(50) PRIMARY KEY, job_title CHAR(50))')

        self.c.executemany('INSERT INTO job_type_data VALUES (?,?,?)', self.job_type_list,)
        self.conn.commit()
        return self.conn.commit()

#
# db_type = job_type_db()
# db_type.db_create()

